### ISSUE TITLE
Horizontal Regression

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/play-ball#7]
**OS X High Sierra Safari_11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/116598736-cec99e00-a8ec-11eb-9bf2-51d4700f3660.gif)
**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/116598751-d12bf800-a8ec-11eb-84d1-69e90e52b5d8.gif)
**Windows 10 Edge_18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/116598753-d1c48e80-a8ec-11eb-9390-4aafd5561d78.gif)

**Comment by vv-monsalve** [comment]
Spacing and kerning fixes were needed

<img width="936" alt="Screen Shot 2021-05-05 at 22 16 01" src="https://user-images.githubusercontent.com/48698976/117242912-d52fac80-adfb-11eb-8ad1-4c9896a41c52.png">
<img width="906" alt="Screen Shot 2021-05-05 at 22 07 50" src="https://user-images.githubusercontent.com/48698976/117242924-d95bca00-adfb-11eb-8448-2bc32ddc25dc.png">

**Comment by vv-monsalve** [comment]
Last result after fixes

**OS X High Sierra Safari_11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/117243098-250e7380-adfc-11eb-95ae-1a19d34050ac.gif)
**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/117243091-217aec80-adfc-11eb-87f9-7d965c27e149.gif)
**Windows 10 Edge_18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/117243095-2475dd00-adfc-11eb-9930-fc69e77cd1e5.gif)

**Comment by davelab6** [comment]
Looks good
